version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/usr/share/nginx/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf